from __future__ import annotations

import os
import shutil
import subprocess
from collections.abc import Iterable
from pathlib import Path

from sneeze.command import CommandError
from sneeze.commandinvariant import InvariantAwareCommand
from sneeze.invariant import (
    BoolInvariant,
    DirectoryInvariant,
    NonNegativeIntegerInvariant,
    PositiveIntegerInvariant,
    StringInvariant,
)

from .ocr_vllm import DEFAULT_OCR_MODEL

DEFAULT_OCR_ENV_NAME = "sneeze-ocr-vllm"
DEFAULT_TORCH_BACKEND = "cu130"
DEFAULT_PYTHON_VERSION = "3.12"
DEFAULT_CUDA_130_VLLM_WHEEL_INDEX = "https://wheels.vllm.ai/nightly/cu130/"


class TpnPluginInfo(InvariantAwareCommand):
    """Show basic information about this plugin."""

    def run(self):
        self._out("sneeze plugin: tpn")


class PdfToPages(InvariantAwareCommand):
    """Render PDFs into page PNG/text files for later OCR.

    Requires Poppler: `pdftocairo` for PNG rendering and `pdftotext` unless
    `--no-text` is used. Use the generated page tree with
    `sne ocr-pdf-pages`.
    """

    _verbose_ = True

    source_dir = None
    _source_dir = None

    class SourceDirArg(DirectoryInvariant):
        _help = "Source directory containing PDF files."

    dest_dir = None
    _dest_dir = None

    class DestDirArg(StringInvariant):
        _help = (
            "Destination root for per-PDF page directories. Defaults to "
            "<source-dir>."
        )
        _mandatory = False

    recursive = None

    class RecursiveArg(BoolInvariant):
        _help = "Recursively process PDF files. [default: %default]"
        _mandatory = False
        _default = False

    parallelism = None
    _parallelism = None

    class ParallelismArg(NonNegativeIntegerInvariant):
        _help = (
            "Parallel worker count; 0 means CPU count. "
            "[default: %default]"
        )
        _mandatory = False
        _default = 0

    limit = None
    _limit = None

    class LimitArg(PositiveIntegerInvariant):
        _help = "Limit the number of PDFs to process."
        _mandatory = False

    dpi = None
    _dpi = None

    class DpiArg(PositiveIntegerInvariant):
        _help = "Render DPI for page images. [default: %default]"
        _mandatory = False
        _default = 400

    force = None

    class ForceArg(BoolInvariant):
        _help = "Re-render existing page images/text. [default: %default]"
        _mandatory = False
        _default = False

    no_text = None

    class NoTextArg(BoolInvariant):
        _help = "Skip per-page text extraction. [default: %default]"
        _mandatory = False
        _default = False

    def run(self):
        from .pdf_pages import (
            build_pdf_page_tasks,
            build_pdf_pages_tasks,
            extract_pdf_page_and_text,
            prepare_pdf_pages_tasks,
            run_tasks_in_threads,
            write_encrypted_sentinels,
        )

        source_dir = _option_value(
            self,
            "source_dir",
            private_first=True,
        )
        dest_dir = os.path.abspath(
            _option_value(self, "dest_dir", source_dir)
        )
        extract_text = not bool(self.no_text)
        workers = _resolve_workers(self._parallelism)
        os.makedirs(dest_dir, exist_ok=True)

        self._out(f"Scanning for PDFs under {source_dir}...")
        tasks = build_pdf_pages_tasks(
            source_dir,
            dest_dir,
            recursive=bool(self.recursive),
            limit=self._limit,
            text_root=dest_dir if extract_text else None,
        )
        if not tasks:
            self._out("No PDFs found.")
            return

        self._out(
            f"Found {len(tasks)} PDF(s); preparing with {workers} worker(s)."
        )
        tasks, skipped = prepare_pdf_pages_tasks(
            tasks,
            max_workers=workers,
        )
        _report_skipped_pdfs(skipped, self._out)
        if not tasks:
            self._out("No readable PDFs found.")
            return

        page_tasks = build_pdf_page_tasks(
            tasks,
            extract_text=extract_text,
            force=bool(self.force),
            dpi=self._dpi or 400,
        )
        if not page_tasks:
            self._out("No PDF pages need extraction.")
            return

        run_tasks_in_threads(
            page_tasks,
            extract_pdf_page_and_text,
            max_workers=workers,
            desc="Extracting PDF pages",
        )
        written = write_encrypted_sentinels(skipped)
        if written:
            label = "sentinel" if len(written) == 1 else "sentinels"
            self._out(f"Wrote {len(written)} .encrypted {label}.")


class PdfsToPages(PdfToPages):
    """Compatibility alias for `sne pdf-to-pages`.

    See `sne pdf-to-pages --help` for Poppler requirements and workflow.
    """


class OcrPdfPages(InvariantAwareCommand):
    """OCR page images generated by `sne pdf-to-pages`.

    Before running, render pages with `sne pdf-to-pages`, create a vLLM env
    with `sne deepseek-ocr-create-env`, and cache the model with
    `sne deepseek-ocr-download-model`. Run this command inside that env.
    Use `--prompt-mode full` to write `.ocr`, `.md`, and `.json` page
    bundles from existing page images. HTML output is a separate
    `--output-format html` mode, not part of `full`.
    """

    _verbose_ = True

    source_dir = None
    _source_dir = None

    class SourceDirArg(DirectoryInvariant):
        _help = "Directory containing page PNG images."

    dest_dir = None
    _dest_dir = None

    class DestDirArg(StringInvariant):
        _help = (
            "Destination directory for OCR output. "
            "[default: <source-dir>]"
        )
        _mandatory = False

    text_source_dir = None
    _text_source_dir = None

    class TextSourceDirArg(DirectoryInvariant):
        _help = (
            "Directory containing per-page extracted text. Defaults to "
            "<source-dir> if present."
        )
        _mandatory = False

    output_format = None
    _output_format = None

    class OutputFormatArg(StringInvariant):
        _help = "Output format: md, html, or ocr. [default: %default]"
        _mandatory = False
        _default = "md"

    model = None
    _model = None

    class ModelArg(StringInvariant):
        _help = "DeepSeek OCR model name or local path. [default: %default]"
        _mandatory = False
        _default = DEFAULT_OCR_MODEL

    prompt = None
    _prompt = None

    class PromptArg(StringInvariant):
        _help = "Override the OCR prompt. `<image>` is added if omitted."
        _mandatory = False

    prompt_mode = None
    _prompt_mode = None

    class PromptModeArg(StringInvariant):
        _help = (
            "Prompt mode: plain_ocr, markdown, html, or full. "
            "[default: %default]"
        )
        _mandatory = False
        _default = "markdown"

    keep_grounding = None

    class KeepGroundingArg(BoolInvariant):
        _help = "Keep DeepSeek grounding tags in output. [default: %default]"
        _mandatory = False
        _default = False

    no_grounding = None

    class NoGroundingArg(BoolInvariant):
        _help = "Do not request grounding tags. [default: %default]"
        _mandatory = False
        _default = False

    limit = None
    _limit = None

    class LimitArg(PositiveIntegerInvariant):
        _help = "Limit the number of pages to OCR."
        _mandatory = False

    offset = None
    _offset = None

    class OffsetArg(NonNegativeIntegerInvariant):
        _help = "Skip the first N page images before --limit."
        _mandatory = False
        _default = 0

    scan_parallelism = None
    _scan_parallelism = None

    class ScanParallelismArg(NonNegativeIntegerInvariant):
        _help = (
            "Workers for startup page discovery; 0 means auto. "
            "[default: %default]"
        )
        _mandatory = False
        _default = 0

    batch_size = None
    _batch_size = None

    class BatchSizeArg(PositiveIntegerInvariant):
        _help = "Client-side OCR batch size."
        _mandatory = False

    enable_chunked_prefill = None

    class EnableChunkedPrefillArg(BoolInvariant):
        _help = "Enable vLLM chunked prefill. [default: %default]"
        _mandatory = False
        _default = True

    max_model_len = None
    _max_model_len = None

    class MaxModelLenArg(PositiveIntegerInvariant):
        _help = "vLLM max_model_len."
        _mandatory = False

    max_num_batched_tokens = None
    _max_num_batched_tokens = None

    class MaxNumBatchedTokensArg(PositiveIntegerInvariant):
        _help = "vLLM max_num_batched_tokens."
        _mandatory = False

    max_num_seqs = None
    _max_num_seqs = None

    class MaxNumSeqsArg(PositiveIntegerInvariant):
        _help = "vLLM max_num_seqs."
        _mandatory = False

    attention_backend = None
    _attention_backend = None

    class AttentionBackendArg(StringInvariant):
        _help = "vLLM attention_backend override."
        _mandatory = False

    mm_encoder_attn_backend = None
    _mm_encoder_attn_backend = None

    class MmEncoderAttnBackendArg(StringInvariant):
        _help = "vLLM multimodal encoder attention backend override."
        _mandatory = False

    scheduler_delay_factor = None
    _scheduler_delay_factor = None

    class SchedulerDelayFactorArg(StringInvariant):
        _help = "vLLM scheduler_delay_factor."
        _mandatory = False

    tensor_parallel_size = None
    _tensor_parallel_size = None

    class TensorParallelSizeArg(PositiveIntegerInvariant):
        _help = "vLLM tensor_parallel_size."
        _mandatory = False

    gpu_memory_utilization = None
    _gpu_memory_utilization = None

    class GpuMemoryUtilizationArg(StringInvariant):
        _help = "vLLM gpu_memory_utilization."
        _mandatory = False

    temperature = None
    _temperature = None

    class TemperatureArg(StringInvariant):
        _help = "Sampling temperature. [default: %default]"
        _mandatory = False
        _default = "0.0"

    max_tokens = None
    _max_tokens = None

    class MaxTokensArg(PositiveIntegerInvariant):
        _help = "Max output tokens per page. [default: %default]"
        _mandatory = False
        _default = 8192

    ngram_size = None
    _ngram_size = None

    class NgramSizeArg(PositiveIntegerInvariant):
        _help = "DeepSeek OCR n-gram size. [default: %default]"
        _mandatory = False
        _default = 10

    window_size = None
    _window_size = None

    class WindowSizeArg(PositiveIntegerInvariant):
        _help = "DeepSeek OCR window size. [default: %default]"
        _mandatory = False
        _default = 50

    force = None

    class ForceArg(BoolInvariant):
        _help = (
            "Re-run OCR when output files already exist. "
            "[default: %default]"
        )
        _mandatory = False
        _default = False

    def run(self):
        from .ocr_vllm import (
            DeepSeekOcrOfflineProcessor,
            collect_ocr_full_items,
            collect_ocr_tasks,
            resolve_scan_workers,
        )

        source_dir = _option_value(
            self,
            "source_dir",
            private_first=True,
        )
        dest_dir = os.path.abspath(
            _option_value(self, "dest_dir", source_dir)
        )
        os.makedirs(dest_dir, exist_ok=True)

        output_format = _option_value(self, "output_format", "md")
        output_format = output_format.lower().strip()
        if output_format not in {"md", "html", "ocr"}:
            raise CommandError("--output-format must be md, html, or ocr")
        prompt_mode = _option_value(self, "prompt_mode", "markdown")
        prompt_mode = prompt_mode.lower().strip()
        if prompt_mode not in {"plain_ocr", "markdown", "html", "full"}:
            raise CommandError(
                "--prompt-mode must be plain_ocr, markdown, html, or full"
            )
        if prompt_mode == "full" and output_format != "md":
            raise CommandError(
                "--prompt-mode full writes .ocr, .md, and .json and "
                "requires --output-format md"
            )
        output_ext = "ocr" if output_format == "ocr" else output_format
        text_source_dir = _option_value(
            self,
            "text_source_dir",
            private_first=True,
        )
        if text_source_dir is None and os.path.isdir(f"{source_dir}.txt"):
            text_source_dir = f"{source_dir}.txt"
        elif text_source_dir is None:
            text_source_dir = source_dir

        scan_workers = resolve_scan_workers(self._scan_parallelism)
        self._out(f"Scanning page images under {source_dir}...")
        items = []
        if prompt_mode == "full":
            items, pdf_count = collect_ocr_full_items(
                source_dir=source_dir,
                dest_dir=dest_dir,
                text_source_dir=text_source_dir,
                force=bool(self.force),
                scan_parallelism=scan_workers,
                out=self._out,
            )
            if self._offset:
                items = items[self._offset :]
            if self._limit:
                items = items[: self._limit]
            if not items:
                self._out("No page images need full OCR.")
                return
            work_count = len(items)
        else:
            tasks, pdf_count = collect_ocr_tasks(
                source_dir=source_dir,
                dest_dir=dest_dir,
                text_source_dir=text_source_dir,
                output_ext=output_ext,
                force=bool(self.force),
                scan_parallelism=scan_workers,
                out=self._out,
            )
            if self._offset:
                tasks = tasks[self._offset :]
            if self._limit:
                tasks = tasks[: self._limit]
            if not tasks:
                self._out("No page images found to OCR.")
                return
            work_count = len(tasks)

        self._out(f"Found {work_count} page(s) across {pdf_count} PDF(s).")
        self._out(f"Writing OCR output to {dest_dir}.")
        try:
            processor = DeepSeekOcrOfflineProcessor(
                model=_option_value(self, "model", DEFAULT_OCR_MODEL),
                output_format=output_format,
                prompt=_option_value(self, "prompt"),
                prompt_mode=(
                    "plain_ocr" if prompt_mode == "full" else prompt_mode
                ),
                keep_grounding=bool(self.keep_grounding),
                use_grounding=False if self.no_grounding else None,
                batch_size=self._batch_size,
                enable_chunked_prefill=bool(self.enable_chunked_prefill),
                max_model_len=self._max_model_len,
                max_num_batched_tokens=self._max_num_batched_tokens,
                max_num_seqs=self._max_num_seqs,
                attention_backend=_option_value(self, "attention_backend"),
                mm_encoder_attn_backend=_option_value(
                    self,
                    "mm_encoder_attn_backend",
                ),
                scheduler_delay_factor=_maybe_float(
                    _option_value(self, "scheduler_delay_factor")
                ),
                tensor_parallel_size=self._tensor_parallel_size,
                gpu_memory_utilization=_maybe_float(
                    _option_value(self, "gpu_memory_utilization")
                ),
                temperature=_maybe_float(
                    _option_value(self, "temperature"),
                    default=0.0,
                ),
                max_tokens=self._max_tokens or 8192,
                ngram_size=self._ngram_size or 10,
                window_size=self._window_size or 50,
                out=self._out,
                verbose=self._verbose,
            )
            if prompt_mode == "full":
                self._run_full_mode(processor, items)
            else:
                processor.run(tasks)
        except RuntimeError as exc:
            raise CommandError(str(exc)) from exc

    def _run_full_mode(self, processor, items) -> None:
        from .ocr_vllm import OcrPageTask, write_ocr_page_bundle

        ocr_tasks = [
            OcrPageTask(
                image_path=item.image_path,
                output_path=item.ocr_path,
                text_source_path=item.text_path,
            )
            for item in items
            if item.need_ocr
        ]
        markdown_tasks = [
            OcrPageTask(
                image_path=item.image_path,
                output_path=item.markdown_path,
                text_source_path=item.text_path,
            )
            for item in items
            if item.need_markdown
        ]
        total_actions = len(ocr_tasks) + len(markdown_tasks) + len(items)
        llm = None
        sampling_params = None
        try:
            processor.init_progressbar(total=total_actions)
            if ocr_tasks or markdown_tasks:
                llm, sampling_params = processor.prepare_engine()
            if ocr_tasks:
                processor.output_format = "ocr"
                processor.prompt_mode = "plain_ocr"
                processor.use_grounding = True
                processor.keep_grounding = True
                processor.run(
                    ocr_tasks,
                    llm=llm,
                    sampling_params=sampling_params,
                )
            if markdown_tasks:
                processor.output_format = "md"
                processor.prompt_mode = "markdown"
                processor.use_grounding = False
                processor.keep_grounding = False
                processor.run(
                    markdown_tasks,
                    llm=llm,
                    sampling_params=sampling_params,
                )
            for item in items:
                write_ocr_page_bundle(item)
                processor.update_progressbar(1)
        finally:
            processor.close_progressbar()
            processor.shutdown_engine(llm)


class DeepseekOcrCreateEnv(InvariantAwareCommand):
    """Create/update a conda environment for `sne ocr-pdf-pages`.

    Installs Python, Poppler, PyTorch, vLLM, and plugin dependencies needed to
    run DeepSeek OCR locally.

    Next: use `sne deepseek-ocr-download-model` to cache the OCR model.
    """

    env_name = None
    _env_name = None

    class EnvNameArg(StringInvariant):
        _help = "Conda/mamba environment name. [default: %default]"
        _mandatory = False
        _default = DEFAULT_OCR_ENV_NAME

    python = None
    _python = None

    class PythonArg(StringInvariant):
        _help = "Python version for the environment. [default: %default]"
        _mandatory = False
        _default = DEFAULT_PYTHON_VERSION

    manager = None
    _manager = None

    class ManagerArg(StringInvariant):
        _help = "Environment manager executable; auto-detects mamba/conda."
        _mandatory = False

    torch_backend = None
    _torch_backend = None

    class TorchBackendArg(StringInvariant):
        _help = "PyTorch wheel backend, for example cu130 or cu121."
        _mandatory = False
        _default = DEFAULT_TORCH_BACKEND

    vllm_package = None
    _vllm_package = None

    class VllmPackageArg(StringInvariant):
        _help = "vLLM package spec. [default: %default]"
        _mandatory = False
        _default = "vllm"

    editable_root = None
    _editable_root = None

    class EditableRootArg(StringInvariant):
        _help = "Install this plugin editable from the given repo root."
        _mandatory = False

    package_spec = None
    _package_spec = None

    class PackageSpecArg(StringInvariant):
        _help = "Package spec to install if --editable-root is not set."
        _mandatory = False
        _default = "sneeze-plugin-tpn[pdf,ocr]"

    dry_run = None

    class DryRunArg(BoolInvariant):
        _help = "Print commands without executing them. [default: %default]"
        _mandatory = False
        _default = False

    def run(self):
        manager = _resolve_manager(self.manager or self._manager)
        env_name = self.env_name or self._env_name or DEFAULT_OCR_ENV_NAME
        python_version = self.python or self._python or DEFAULT_PYTHON_VERSION
        torch_backend = (
            self.torch_backend or self._torch_backend or DEFAULT_TORCH_BACKEND
        )
        vllm_package = self.vllm_package or self._vllm_package or "vllm"
        editable_root = self._editable_root or self.editable_root
        package_spec = (
            self._package_spec
            or self.package_spec
            or "sneeze-plugin-tpn[pdf,ocr]"
        )
        commands = build_ocr_env_commands(
            manager=manager,
            env_name=env_name,
            python_version=python_version,
            torch_backend=torch_backend,
            vllm_package=vllm_package,
            editable_root=editable_root,
            package_spec=package_spec,
        )
        _run_or_print(commands, dry_run=bool(self.dry_run), out=self._out)


class DeepseekOcrDownloadModel(InvariantAwareCommand):
    """Download/cache the DeepSeek OCR model for `sne ocr-pdf-pages`.

    Usually run this after `sne deepseek-ocr-create-env`, optionally with
    `--env-name`, so the model is present before the first OCR run.
    """

    model = None
    _model = None

    class ModelArg(StringInvariant):
        _help = "Hugging Face model ID. [default: %default]"
        _mandatory = False
        _default = DEFAULT_OCR_MODEL

    local_dir = None
    _local_dir = None

    class LocalDirArg(StringInvariant):
        _help = "Optional destination directory."
        _mandatory = False

    revision = None
    _revision = None

    class RevisionArg(StringInvariant):
        _help = "Optional model revision."
        _mandatory = False

    env_name = None
    _env_name = None

    class EnvNameArg(StringInvariant):
        _help = "Run the download inside this conda/mamba environment."
        _mandatory = False

    manager = None
    _manager = None

    class ManagerArg(StringInvariant):
        _help = "Environment manager executable; auto-detects mamba/conda."
        _mandatory = False

    dry_run = None

    class DryRunArg(BoolInvariant):
        _help = "Print the command without executing it. [default: %default]"
        _mandatory = False
        _default = False

    def run(self):
        command = build_model_download_command(
            model=self.model or self._model or DEFAULT_OCR_MODEL,
            local_dir=self._local_dir or self.local_dir,
            revision=self._revision or self.revision,
            env_name=self._env_name or self.env_name,
            manager=self._manager or self.manager,
        )
        _run_or_print([command], dry_run=bool(self.dry_run), out=self._out)


def build_ocr_env_commands(
    *,
    manager: str,
    env_name: str,
    python_version: str,
    torch_backend: str,
    vllm_package: str,
    editable_root: str | None,
    package_spec: str,
) -> list[list[str]]:
    pytorch_index = f"https://download.pytorch.org/whl/{torch_backend}"
    commands = [
        [
            manager,
            "create",
            "-n",
            env_name,
            "-y",
            "-c",
            "conda-forge",
            f"python={python_version}",
            "pip",
            "uv",
            "poppler",
        ],
        [
            manager,
            "run",
            "-n",
            env_name,
            "python",
            "-m",
            "pip",
            "install",
            "-U",
            "pip",
        ],
        [
            manager,
            "run",
            "-n",
            env_name,
            "uv",
            "pip",
            "install",
            "-U",
            "huggingface_hub",
            "pdf2image",
            "pillow",
            "tqdm",
            "transformers",
        ],
        [
            manager,
            "run",
            "-n",
            env_name,
            "uv",
            "pip",
            "install",
            "-U",
            "--pre",
            "torch",
            "torchvision",
            "torchaudio",
            "--index-url",
            pytorch_index,
        ],
    ]
    vllm_command = [
        manager,
        "run",
        "-n",
        env_name,
        "uv",
        "pip",
        "install",
        "-U",
        "--pre" if torch_backend == "cu130" else "",
        vllm_package,
    ]
    vllm_command = [part for part in vllm_command if part]
    if torch_backend == "cu130":
        vllm_command.extend(
            ["--extra-index-url", DEFAULT_CUDA_130_VLLM_WHEEL_INDEX]
        )
    commands.append(vllm_command)
    if editable_root:
        commands.append(
            [
                manager,
                "run",
                "-n",
                env_name,
                "python",
                "-m",
                "pip",
                "install",
                "-e",
                editable_root,
            ]
        )
    else:
        commands.append(
            [
                manager,
                "run",
                "-n",
                env_name,
                "python",
                "-m",
                "pip",
                "install",
                "-U",
                package_spec,
            ]
        )
    return commands


def build_model_download_command(
    *,
    model: str,
    local_dir: str | None,
    revision: str | None,
    env_name: str | None,
    manager: str | None,
) -> list[str]:
    code = (
        "import sys\n"
        "from huggingface_hub import snapshot_download\n"
        "model, local_dir, revision = sys.argv[1:4]\n"
        "kwargs = {'repo_id': model}\n"
        "if local_dir:\n"
        "    kwargs['local_dir'] = local_dir\n"
        "if revision:\n"
        "    kwargs['revision'] = revision\n"
        "print(snapshot_download(**kwargs))\n"
    )
    command = [
        "python",
        "-c",
        code,
        model,
        local_dir or "",
        revision or "",
    ]
    if env_name:
        manager_bin = _resolve_manager(manager)
        return [manager_bin, "run", "-n", env_name, *command]
    return command


def _report_skipped_pdfs(skipped, out) -> None:
    if not skipped:
        return
    encrypted = [item for item in skipped if item.is_encrypted]
    unreadable = [item for item in skipped if not item.is_encrypted]
    label = "PDF" if len(skipped) == 1 else "PDFs"
    out(f"Skipped {len(skipped)} {label}:")
    if encrypted:
        enc_label = "PDF" if len(encrypted) == 1 else "PDFs"
        out(f"  {len(encrypted)} password-protected {enc_label}")
    if unreadable:
        read_label = "PDF" if len(unreadable) == 1 else "PDFs"
        out(f"  {len(unreadable)} unreadable {read_label}")
    for item in skipped:
        out(f"  {item.source_path}")
        out(f"    {item.error}")


def _resolve_workers(value: int | None) -> int:
    workers = int(value or 0)
    if workers <= 0:
        return os.cpu_count() or 1
    return workers


def _option_value(
    command,
    name: str,
    default=None,
    *,
    private_first: bool = False,
):
    names = (
        (f"_{name}", name)
        if private_first
        else (name, f"_{name}")
    )
    for attr_name in names:
        value = getattr(command, attr_name, None)
        if value not in (None, ""):
            return value
    return default


def _maybe_float(value, default=None):
    if value in (None, ""):
        return default
    try:
        return float(value)
    except (TypeError, ValueError) as exc:
        raise CommandError(f"Expected a float, got {value!r}") from exc


def _resolve_manager(value: str | None) -> str:
    if value:
        return value
    for candidate in ("mamba", "conda"):
        path = shutil.which(candidate)
        if path:
            return path
    raise CommandError("Could not find mamba or conda on PATH")


def _run_or_print(
    commands: Iterable[list[str]],
    *,
    dry_run: bool,
    out,
) -> None:
    for command in commands:
        out(" ".join(_quote(arg) for arg in command))
        if dry_run:
            continue
        completed = subprocess.run(command, check=False)
        if completed.returncode != 0:
            raise CommandError(
                f"Command failed with exit status {completed.returncode}"
            )


def _quote(value: str) -> str:
    import shlex

    return shlex.quote(str(value))


def package_root() -> str:
    return str(Path(__file__).resolve().parents[3])
